Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='myapp')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('myapp.api_urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from .views import *
app_name = 'myapp'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<slug>', ItemListView.as_view(),  name='category'),
    path('products/<slug>', ItemDetailView.as_view(), name='products'),
    path('contact/', contact, name='contact'),
    path('search/', SearchView.as_view(), name='search'),
    path('account/', signup, name='account'),
    path('review/', review_item, name='review'),
    path('cart/<slug>', cart, name='cart'),
    path('my_cart/', CartView.as_view(), name='my_cart'),
    path('delete_cart/<slug>', delete_cart, name='delete_cart'),
    path('delete_single_cart/<slug>', delete_single_cart, name='delete_single_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
]

myapp/views.py
from django.conf import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.shortcuts import render, redirect
from django.views.generic.base import View, TemplateView
from .models import *
from django.contrib import messages


class BaseView(View):
    views = dict()
    views['sliders'] = Slider.objects.filter(status='active')
    views['brands'] = Brand.objects.filter(status='active')
    views['item_count'] = Product.objects.count()
    views['items'] = Product.objects.filter(status='active')
    views['cat_details'] = Category.objects.filter(status='active')
    views['cats_count'] = []
    for i in views['cat_details']:
        count_item = Product.objects.filter(category=i.id).count()
        a = {'cats': i.title, 'image': i.image, 'cat_count': count_item, 'url': i.get_cat_url}
        views['cats_count'].append(a)

    views['brand_details'] = Brand.objects.filter(status='active')
    views['brands_count'] = []
    for i in views['brand_details']:
        count_brand = Product.objects.filter(brand=i.id).count()
        b = {'brands': i.name, 'brand_count': count_brand}
        views['brands_count'].append(b)


class HomeView(BaseView):
    def get(self, request):
        user = request.user.username
        self.views['ads'] = Ad.objects.filter(status='active')
        self.views['hots'] = Product.objects.filter(label='hot', status='active')
        self.views['news'] = Product.objects.filter(label='new', status='active')
        self.views['most_viewed'] = Product.objects.filter(label='most_viewed', status='active')
        self.views['defaults'] = Product.objects.filter(label='', status='passive')
        self.views['site_reviews'] = SiteReview.objects.filter(status='active')
        return render(request, 'index.html', self.views)


class ItemDetailView(BaseView):
    def get(self, request, slug):
        self.views['item_detail'] = Product.objects.filter(slug=slug)
        item_ids = Product.objects.get(slug=slug).category_id
        self.views['item_cats'] = Product.objects.filter(category=item_ids)
        self.views['reviews'] = Review.objects.filter(slug=slug, status='active')
        return render(request, 'product-detail.html', self.views)


class ItemListView(BaseView):
    def get(self, request, slug):
        cat_ids = Category.objects.get(slug=slug).id
        self.views['cat_items'] = Product.objects.filter(category=cat_ids)
        return render(request, 'product-list.html', self.views)


class SearchView(BaseView):
    def get(self, request):
        if request.method == 'GET':
            query = request.GET['search']
            self.views['search_product'] = Product.objects.filter(name__icontains=query)
            return render(request, 'search.html', self.views)
        return render(request, 'search.html')


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        contact_data = Contact.objects.create(
            name=name,
            email=email,
            subject=subject,
            message=message
        )
        if len(name) < 3 or len(message) < 5 or len(email) < 4:
            messages.error(request, '❌ Please re-enter the contact form!')
            return redirect('myapp:contact')
        else:
            send_email = EmailMessage(
                'contact from your website',
                f'Hello, the contact of {name} is saved, the email is {email}. and the contact has the subject named "{subject}".'
                f' The message is {message}.',
                settings.EMAIL_HOST_USER,
                ['nabinghimire1001@gmail.com'],
                # [request.user.email],
                [email],
            )
            send_email.fail_silently = False
            send_email.send()
            contact_data.save()
            return redirect('/', kwargs={'messages': messages.success(request, '✔ Contact Saved and an'
                                                                               ' email is sent to you.')})
    return render(request, 'contact.html')


def signup(request):
    Cart.objects.all().delete()
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        fname = request.POST['fname']
        lname = request.POST['lname']

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.error(request, '❌ This username is already taken!')
                return redirect('myapp:account')
            elif User.objects.filter(email=email).exists():
                messages.error(request, '❌ This email is already taken!')
                return redirect('myapp:account')
            else:
                user = User.objects.create_user(
                    username=username,
                    email=email,
                    password=password,
                    first_name=fname,
                    last_name=lname
                )
                user.save()
                messages.success(request, '✔️You are registered! Continue to login!')
                return redirect('/accounts/login', messages)
        else:
            messages.error(request, '❌ These passwords do not match!')
            return redirect('myapp:account')
    return render(request, 'signup.html')


# def login(request):
#     user = request.user.username
#     if user.is_authenticated:
#         messages.success(request, f'✔️You are logged in as! {user}')
#         return redirect('myapp:home', messages)


def review_item(request):
    if request.method == 'POST':
        rating = request.POST['rating']
        review = request.POST['review']
        username = request.user.username
        email = request.user.email
        slug = request.POST['slug']

        user_review = Review.objects.create(
            rating=rating,
            username=username,
            review=review,
            email=email,
            slug=slug
        )
        user_review.save()
        messages.success(request, '✔️Your review is successfully submitted!')
        return redirect(f'/products/{slug}')


def cart(request, slug):
    price = Product.objects.get(slug=slug).price
    discounted_price = Product.objects.get(slug=slug).discounted_price
    user = request.user.username
    net_total = 0
    shipping_cost = 1000
    if Cart.objects.filter(slug=slug).exists():
        quantity = Cart.objects.get(username=user, slug=slug, checkout=False).quantity
        qty = quantity + 1
        if discounted_price > 0:
            actual_total = discounted_price * qty
        else:
            actual_total = price * qty
        Cart.objects.filter(username=user, slug=slug, checkout=False).update(
            quantity=qty, total=actual_total)

        total = Cart.objects.filter(username=user, checkout=False, status='active')

        for i in total[:]:
            net_total += i.total
        grand_total = net_total + shipping_cost

        CartTotal.objects.filter(username=user, checkout=False).update(
            net_total=net_total, shipping_cost=shipping_cost, grand_total=grand_total)
        return redirect('myapp:my_cart')

    else:
        if discounted_price > 0:
            actual_total = discounted_price * 1
        else:
            actual_total = price * 1
        data = Cart.objects.create(
            username=user,
            slug=slug,
            quantity=1,
            total=actual_total,
            products=Product.objects.filter(slug=slug)[0]

        )
        Cart.objects.filter(username=user, slug=slug, checkout=False).update(checkout=False, total=actual_total)
        total = Cart.objects.filter(username=user, checkout=False, status='active')

        for i in total[:]:
            net_total += i.total
        grand_total = net_total + shipping_cost
        data1 = CartTotal.objects.create(
            username=user,
            slug=slug,
            net_total=net_total,
            shipping_cost=shipping_cost,
            grand_total=grand_total,
            cart=Cart.objects.filter(slug=slug)[0]
        )
        if request.user.is_authenticated:
            data.save()
            data1.save()
            messages.success(request, f'✔️The item "{slug}" is added in cart!')
        else:
            messages.error(request, 'please Sign Up first!')
            return redirect('myapp:account')

        CartTotal.objects.filter(username=user, checkout=False).update(net_total=net_total, shipping_cost=shipping_cost, grand_total=grand_total)
        return redirect('myapp:my_cart')


class CartView(BaseView):
    def get(self, request):
        user = request.user.username
        net_total = 0
        shipping_cost = 1000
        grand_total = 0
        if request.user.is_authenticated:
            self.views['cart_product'] = Cart.objects.filter(username=user, checkout=False, status='active')
            tots = CartTotal.objects.filter(username=user, checkout=False)
            for i in tots[:]:
                net_total = i.net_total
                shipping_cost = i.shipping_cost
                grand_total = i.grand_total
            self.views['cart_total'] = [{'net_total': net_total, 'shipping_cost': shipping_cost, 'grand_total': grand_total}]
            self.views['cart_count'] = Cart.objects.filter(username=user, status='active', checkout=False).count()
        else:
            messages.error(request, 'please Sign up first!')
            return redirect('myapp:account')
        return render(request, 'cart.html', self.views)


def delete_cart(request, slug):
    if Cart.objects.filter(slug=slug).exists():
        user = request.user.username
        net_total = 0
        t = 0
        shipping_cost = 1000

myapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>E Store - eCommerce HTML Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    {% if user.is_authenticated %}
                    <div class="col-sm-6" style="text-align:center;">
                        <i class="fas fa-user-circle"></i>
                        <h6>username: {{ user.username}}</h6>
                    </div>
                    <div class="col-sm-6" style="text-align:center;">
                        <i class="fas fa-envelope"></i>
                        <h6>email: {{ user.email }}</h6>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Top bar End -->

        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="/" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'myapp:contact' %}" class="dropdown-item">Contact Us</a>
                        </div>
                        <div class="navbar-nav ml-auto">
                            <div class="nav-item dropdown">
                                {% if user.is_authenticated %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ user.username }}</a>
                                <div class="dropdown-menu">
                                    <a href="/accounts/logout" class="dropdown-item">Logout</a>
                                </div>
                                {% else %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">User Account</a>
                                <div class="dropdown-menu">
                                    <a href="/accounts/login" class="dropdown-item">Login</a>
                                    <a href="{% url 'myapp:account' %}" class="dropdown-item">Signup</a>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->

        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="index.html">
                                <img src="{% static 'img/logo1.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form method="GET" action="{% url 'myapp:search' %}">
                        <div class="search">
                            <input name="search" type="text" placeholder="Search">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </div>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <a href="#" class="btn wishlist">
                                <i class="fa fa-heart"></i>
                                <span>(0)</span>
                            </a>
                            <a href="{% url 'myapp:my_cart' %}" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>({{ cart_count }})</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->
    {% block content %}
    {% endblock %}
        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>123 E Store, Los Angeles, USA</p>
                                <p><i class="fa fa-envelope"></i>email@example.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Payment Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="{% static 'img/payment-method.png' %}" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="{% static 'img/godaddy.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/norton.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/ssl.svg' %}" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

myapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Cart</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          <center><strong>Message: </strong>{{ message }}</center>
        </div>
        {% endfor %}
        {% endif %}
        <!-- Cart Start -->
        <div class="cart-page">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Product</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Total</th>
                                            <th>Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                    {% for item in cart_product %}
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <a href="#"><img src="{{item.products.image.url}}" alt="Image"></a>
                                                    <p>{{item.products.name}}</p>
                                                </div>
                                            </td>
                                            {% if item.products.discount > 0 %}
                                                <td>Rs.{{item.products.discounted_price}}</td>
                                            {% else %}
                                                <td>Rs.{{item.products.price}}</td>
                                            {% endif %}
                                            <td>
                                                <div class="qty">
                                                    <a href="/delete_single_cart/{{item.products.slug}}"><button class="btn-minus"><i class="fa fa-minus"></i></button></a>
                                                    <input type="text" value="{{item.quantity}}">
                                                    <a href="{{item.products.get_cart_url}}"><button class="btn-plus"><i class="fa fa-plus"></i></button></a>
                                                </div>
                                            </td>

                                            <td>
                                            Rs.{{ item.total }}
                                            </td>

                                            <td><a href="/delete_cart/{{item.products.slug}}"><button><i class="fa fa-trash"></i></button></a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-page-inner">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="coupon">
                                        <input type="text" placeholder="Coupon Code">
                                        <button>Apply Code</button>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="cart-summary">

                                        <div class="cart-content">
                                            <h1>Cart Summary</h1>
                                            {% for i in cart_total%}
                                            <p>Sub Total - <span>{{ i.net_total}}</span></p>
                                            <p>Shipping Cost - <span>{{ i.shipping_cost }}</span></p>
                                            <h2>Grand Total - <span>{{ i.grand_total }}</span></h2>
                                            {% endfor %}
                                        </div>

                                        <div class="cart-btn">
                                            <a href="{% url 'myapp:checkout' %}"><button type="submit">Checkout</button></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart End -->
        
{% endblock %}

myapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Login & Register</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Login Start -->
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="login-form">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>E-mail / Username</label>
                                    <input name="" class="form-control" type="text" placeholder="E-mail / Username">
                                </div>
                                <div class="col-md-6">
                                    <label>Password</label>
                                    <input name="password" class="form-control" type="password" placeholder="Password">
                                </div>
                                <div class="col-md-12">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="newaccount">
                                        <label class="custom-control-label" for="newaccount">Keep me signed in</label>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="btn">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Login End -->
{% endblock %}